export default {
  LOGIN_SUCESS: '@Bairrista/LOGIN_SUCESS',
  LOGGOUT: '@Bairrista/LOGGOUT',
  APP_LOADED: '@Bairrista/APP_LOADED',
  SAVE_USER: '@Bairrista/SAVE_USER',
  SAVE_CARTOES: '@auth/SAVE_CARTOES',
  SAVE_TOKEN: '@auth/SAVE_TOKEN',
  AUTHENTICADED: '@Bairrista/AUTHENTICADED',
  ESTABELECIMENTO: '@Bairrista/ESTABELECIMENTO',
};
